<h2>Agregar tarea</h2>

<form action="<?php echo APP_URL."tareas/add"; ?>" method="POST">
		<p>Nombre: <input type="text" name="nombre"></p>
		<p>Fecha: <input type="text" name="fecha"></p>
		<p>Prioridad: <input type="text" name="prioridad"></p>
		<p>Estatus: <input type="text" name="status"></p>
		<p>Categorias: 
		<select name="categoria_id"> 
		<option value="">selecciona</option>
		<?php foreach ($this->categorias as $categoria): ?>
			<option value="<?php echo $categoria["id"]; ?>"><?php echo $categoria["nombre"]; ?></option>
		<?php endforeach; ?>
		</select>
		 </p>
		<p><input type="submit"></p>