<h2>Editar tarea</h2>

<form action="<?php echo APP_URL."tareas/edit"; ?>" method="POST">
		<input type="hidden" name="id" value="<?php echo $this->tarea["id"]; ?>">
		<p>Nombre: <input type="text" name="nombre" value="<?php echo $this->tarea["nombre"]; ?>"></p>
		<p>Fecha: <input type="text" name="fecha" value="<?php echo $this->tarea["fecha"]; ?>"></p>
		<p>Prioridad: <input type="text" name="prioridad" value="<?php echo $this->tarea["prioridad"]; ?>"></p>
		<p>Estatus: <input type="text" name="status" value="<?php echo $this->tarea["status"]; ?>"></p>
		<p><input type="submit"></p>
</form>